### ISSUE TITLE
CuQR is not present in CUDA.jl for julia 1.8+

### ISSUE THREAD

**Issue by avik-pal** [SciML/LinearSolve.jl#123]
https://github.com/JuliaGPU/CUDA.jl/blob/f52201036272591b74b994dd7d9df1496ba1f88a/lib/cusolver/linalg.jl#L72 removes CuQR

**Comment by ChrisRackauckas** [comment]
Wait, why @maleadt ? What are we supposed to use here instead in v1.8?

**Comment by maleadt** [comment]
`Base.QR`. See https://github.com/JuliaLang/julia/pull/42594 for https://github.com/JuliaGPU/CUDA.jl/pull/1449 replacing https://github.com/JuliaGPU/CUDA.jl/pull/1194 to fix https://github.com/JuliaGPU/CUDA.jl/issues/1193. This whole change was because you requested support for more factorizations, so I'm surprised about you being surprised 😛

**Comment by ChrisRackauckas** [comment]
Oh I see. Yes, then https://github.com/SciML/LinearSolve.jl/pull/130/files#diff-4c8f9e26491b28a6897e9cf2c7f8d59c2f4c9b5fc66e1067a4d4fd8e3fd98226 solves this issue because enough has been upstreamed that we don't need to carry around those overloads. I forgot everything got upstreamed 😅

**Comment by ChrisRackauckas** [comment]
Solved in https://github.com/SciML/LinearSolve.jl/pull/130
