### ISSUE TITLE
Strange Behavior on Linux vs macos

### ISSUE THREAD

**Issue by iliailmer** [SciML/LinearSolve.jl#243]
I have been working on some code that uses LinearSolve and I ran into a strange behavior depending on OS.

```julia
using LinearSolve
using DelimitedFiles

A = readdlm("A.txt")
b = readdlm("b.txt")

prob = LinearSolve.LinearProblem(A, b)
c = LinearSolve.solve(prob)
```

`A` has a determinant -2.4703845333287813e-50. On macos, the code above produces an answer, on a Linux machine I get a singularity error. Why is the behavior so different?

The input files are here:
[A.txt](https://github.com/SciML/LinearSolve.jl/files/10221307/A.txt)
[b.txt](https://github.com/SciML/LinearSolve.jl/files/10221308/b.txt)

**Comment by ChrisRackauckas** [comment]
That's not strange. Different BLAS implementations, which will change depending on the OS, will use different SIMD vector lengths and summation orders. Changes to multithreading will also change multithreading. Because floating point arithmetic is not associative, that will lead to differences (based on the condition number of the matrix). `-2.4703845333287813e-50` is just indiscernibly close to zero with 64-bit floating points.
